// src/components/game/recipe/RecipeDisplay.tsx
import { GameGuiFrame } from "@/src/components/game/GameGuiFrame";
import { GameText } from "@/src/components/game/GameText";
import { CraftingRecipeDisplay } from "@/src/components/game/recipe/CraftingRecipeDisplay";
import { InfusorRecipeDisplay } from "@/src/components/game/recipe/InfusorRecipeDisplay";
import { RitualRecipeDisplay } from "@/src/components/game/recipe/RitualRecipeDisplay";
import { RitualStructureDisplay } from "@/src/components/game/recipe/RitualStructureDisplay";
import { SoakRecipeDisplay } from "@/src/components/game/recipe/SoakRecipeDisplay";
import { getRecipeData } from "@/src/lib/game/server-data";
import type {
  NormalizedCraftingRecipe,
  NormalizedInfusorRecipe,
  NormalizedRitualRecipe,
  NormalizedRitualStructure,
  NormalizedSoakRecipe,
} from "@/src/lib/game/types";

export async function RecipeDisplay({ id }: { id: string }) {
  try {
    const recipe = await getRecipeData(id);

    return (
      <GameGuiFrame className="recipe-frame">
        <div className="recipe-frame__wrapper">
          <GameText className="recipe-frame__id" color="#3F3F3F" noShadow>
            {id}
          </GameText>
          <div className="recipe-frame__content">
            {recipe.type === "minecraft:crafting_shaped" || recipe.type === "minecraft:crafting_shapeless" ? (
              <CraftingRecipeDisplay recipe={recipe as NormalizedCraftingRecipe} />
            ) : null}
            {recipe.type === "croparia:infusor" ? <InfusorRecipeDisplay recipe={recipe as NormalizedInfusorRecipe} /> : null}
            {recipe.type === "croparia:ritual" ? <RitualRecipeDisplay recipe={recipe as NormalizedRitualRecipe} /> : null}
            {recipe.type === "croparia:soak" ? <SoakRecipeDisplay recipe={recipe as NormalizedSoakRecipe} /> : null}
            {recipe.type === "croparia:ritual_structure" ? (
              <RitualStructureDisplay recipe={recipe as NormalizedRitualStructure} />
            ) : null}
          </div>
        </div>
      </GameGuiFrame>
    );
  } catch {
    return (
      <GameGuiFrame className="recipe-frame">
        <div className="recipe-frame__wrapper">
          <GameText className="recipe-frame__id" color="#3F3F3F" noShadow>
            {id}
          </GameText>
          <GameText className="recipe-frame__error" color="#AA0000" noShadow>
            Recipe unavailable.
          </GameText>
        </div>
      </GameGuiFrame>
    );
  }
}

// .vitepress/theme/components/recipe/RecipeDisplay.vue
<script setup lang="ts">
import {ref, watchEffect} from "vue";
import {Recipe} from "../../type/Recipe";
import CraftingRecipeDisplay from "./CraftingRecipeDisplay.vue";
import GameGuiFrame from "../GameGuiFrame.vue";
import {NormalizedCraftingRecipe} from "../../type/CraftingRecipe";
import GameText from "../GameText.vue";
import InfusorRecipeDisplay from "./InfusorRecipeDisplay.vue";
import {NormalizedInfusorRecipe} from "../../type/InfusorRecipe";
import RitualRecipeDisplay from "./RitualRecipeDisplay.vue";
import {NormalizedRitualRecipe} from "../../type/RitualRecipe";
import SoakRecipeDisplay from "./SoakRecipeDisplay.vue";
import {NormalizedSoakRecipe} from "../../type/SoakRecipe";
import RitualStructureDisplay from "./RitualStructureDisplay.vue";
import {NormalizedRitualStructure} from "../../type/RitualStructure";

const {
  id
} = defineProps<{
  locale?: string,
  id: string
}>();
const recipe = ref<Recipe | undefined>();

watchEffect(async () => {
  recipe.value = await Recipe.fetch(id);
});
</script>

<template>
  <GameGuiFrame class="recipe-frame" v-if="recipe">
    <div class="recipe-wrapper">
      <GameText class="recipe-id" color="#3F3F3F" noShadow>{{ id }}</GameText>
      <CraftingRecipeDisplay class="recipe-content"
                             v-if="recipe.type === 'minecraft:crafting_shaped' || recipe.type === 'minecraft:crafting_shapeless'"
                             :recipe="recipe as NormalizedCraftingRecipe"/>
      <InfusorRecipeDisplay class="recipe-content" v-if="recipe.type=== 'croparia:infusor'"
                            :recipe="recipe as NormalizedInfusorRecipe"/>
      <RitualRecipeDisplay class="recipe-content" v-if="recipe.type === 'croparia:ritual'"
                           :recipe="recipe as NormalizedRitualRecipe"/>
      <SoakRecipeDisplay class="recipe-content" v-if="recipe.type=== 'croparia:soak'"
                         :recipe="recipe as NormalizedSoakRecipe"/>
      <RitualStructureDisplay class="recipe-content" v-if="recipe.type=== 'croparia:ritual_structure'"
                              :recipe="recipe as NormalizedRitualStructure"/>
    </div>
  </GameGuiFrame>
</template>

<style scoped>
.recipe-wrapper {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.recipe-content {
  margin: calc(var(--vp-unit-size) * 4);
}

.recipe-id {
  margin: calc(var(--vp-unit-size) * 2);
}
</style>
