// src/components/game/recipe/SoakRecipeDisplay.tsx
import { GameBlockEntry } from "@/src/components/game/GameBlockEntry";
import { GameItemDisplay } from "@/src/components/game/GameItemDisplay";
import { GameItemEntry } from "@/src/components/game/GameItemEntry";
import type { NormalizedSoakRecipe } from "@/src/lib/game/types";

export async function SoakRecipeDisplay({ recipe }: { recipe: NormalizedSoakRecipe }) {
  return (
    <div className="soak-recipe">
      <GameItemEntry props={recipe.element} />
      <img className="recipe-connector" src="/assets/gui/elem_infuse.webp" alt="element infuse" />
      <GameItemDisplay id="croparia:infusor" />
      <div />
      <div />

      <div />
      <div />
      <img className="recipe-connector" src="/assets/gui/block_place_upon.webp" alt="block place upon" />
      <div />
      <div />

      <GameBlockEntry props={recipe.input} />
      <img className="recipe-connector" src="/assets/gui/elem_infuse.webp" alt="element infuse" />
      <GameItemDisplay id="croparia:infusor" />
      <img className="recipe-arrow" src="/assets/gui/recipe-arrow.webp" alt="recipe arrow" />
      <GameBlockEntry props={recipe.output} />
    </div>
  );
}

// .vitepress/theme/components/recipe/SoakRecipeDisplay.vue
<script setup lang="ts">
import GameItemEntry from "../GameItemEntry.vue";
import GameItemDisplay from "../GameItemDisplay.vue";
import {NormalizedSoakRecipe} from "../../type/SoakRecipe";
import GameBlockEntry from "../GameBlockEntry.vue";

const {
  locale,
  recipe
} = defineProps<{
  locale: string,
  recipe: NormalizedSoakRecipe
}>();

</script>

<template>
  <div class="soak-recipe">
    <GameItemEntry :locale="locale" :props="recipe.element"/>
    <img class="connector" src="assets/gui/elem_infuse.png" alt="element infuse"/>
    <GameItemEntry :locale="locale" props="croparia:infusor"/>
    <div></div>
    <div></div>

    <div></div>
    <div></div>
    <img class="connector" src="assets/gui/block_place_upon.png" alt="item drop"/>
    <div></div>
    <div></div>

    <GameBlockEntry :locale="locale" :props="recipe.input"/>
    <img class="connector" src="assets/gui/elem_infuse.png" alt="element infuse"/>
    <GameItemDisplay :locale="locale" id="croparia:infusor"/>
    <img class="arrow" src='assets/gui/recipe-arrow.png' alt="recipe arrow"/>
    <GameBlockEntry :locale="locale" :props="recipe.output"/>
  </div>
</template>

<style scoped>
.soak-recipe {
  display: grid;
  grid-template-columns: auto auto auto auto auto;
}

.soak-recipe img {
  image-rendering: pixelated;
}

.soak-recipe .connector {
  width: calc(var(--vp-unit-size) * 16);
  height: calc(var(--vp-unit-size) * 16);
}

.soak-recipe .arrow {
  width: calc(var(--vp-unit-size) * 22);
  height: calc(var(--vp-unit-size) * 15);
}
</style>
