// src/components/game/GameArrowButton.tsx
"use client";

type Direction = "up" | "down" | "left" | "right";

interface GameArrowButtonProps {
  direction?: Direction;
  size?: number;
  onClick?: React.MouseEventHandler<HTMLButtonElement>;
  onMouseOver?: React.MouseEventHandler<HTMLButtonElement>;
  disabled?: boolean;
}

export function GameArrowButton({
  direction = "up",
  size = 12,
  onClick,
  onMouseOver,
  disabled = false,
}: GameArrowButtonProps) {
  return (
    <button
      type="button"
      className="game-arrow-button"
      disabled={disabled}
      onClick={onClick}
      onMouseOver={onMouseOver}
      style={{
        width: `calc(var(--vp-unit-size) * ${size})`,
        height: `calc(var(--vp-unit-size) * ${size})`,
        backgroundImage: `url(/assets/gui/arrow-button/${direction}-dark.webp)`,
      }}
      onMouseEnter={(event) => {
        event.currentTarget.style.backgroundImage = `url(/assets/gui/arrow-button/${direction}-white.webp)`;
      }}
      onMouseLeave={(event) => {
        event.currentTarget.style.backgroundImage = `url(/assets/gui/arrow-button/${direction}-dark.webp)`;
      }}
    />
  );
}

// .vitepress/theme/components/GameArrowButton.vue
<script setup lang="ts">
import {withBase} from "vitepress";

const {
  direction = 'up',
  size = 12,
  onHover = () => {},
  onClick = () => {}
} = defineProps<{
  direction?: 'up' | 'down' | 'left' | 'right',
  size?: number,
  onHover?: (event: Event) => void,
  onClick?: (event: Event) => void
}>();

const darkImg = `url(${withBase(`/assets/gui/arrow-button/${direction}-dark.webp`)})`;
const whiteImg = `url(${withBase(`/assets/gui/arrow-button/${direction}-white.webp`)})`;
</script>

<template>
  <div class="game-arrow-button" @mouseover="onHover" @click="onClick"/>
</template>

<style scoped>
.game-arrow-button {
  background-image: v-bind(darkImg);
  background-repeat: no-repeat;
  background-position: left center;
  background-size: auto 100%;
  image-rendering: pixelated;
  width: calc(var(--vp-unit-size) * v-bind(size));
  height: calc(var(--vp-unit-size) * v-bind(size));
}

.game-arrow-button:hover {
  background-image: v-bind(whiteImg);
}
</style>
